version: '3'

services:
  tkltest-cli:
    build:
      context: .
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: tkltest-cli
    volumes:
      - ./:/app/tackle-test-cli
    stdin_open: true
    tty: true
    network_mode: host
