/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 10 10:44:19 GMT 2022
 */

package irs;

import org.junit.Test;
import static org.junit.Assert.*;
import irs.Employee;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Employee_ESTest extends Employee_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Employee employee0 = new Employee();
      int int0 = employee0.getHours();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Employee employee0 = new Employee();
      employee0.setHours((-748));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Employee employee0 = new Employee();
      employee0.setLevel("S)ot0%xCTzVxGpt+");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Employee employee0 = new Employee();
      String string0 = employee0.getName();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Employee employee0 = new Employee((-1739), "", 0, 0);
      double double0 = employee0.getRate();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Employee employee0 = new Employee();
      employee0.setName("");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Employee employee0 = new Employee();
      String string0 = employee0.getLevel();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Employee employee0 = new Employee();
      employee0.setRate(2344);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Employee employee0 = new Employee();
      employee0.setEmployeeId((-748));
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Employee employee0 = new Employee();
      int int0 = employee0.getEmployeeId();
  }
}
