/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 10 10:45:12 GMT 2022
 */

package irs;

import org.junit.Test;
import static org.junit.Assert.*;
import irs.Employee;
import irs.Employer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Employer_ESTest extends Employer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Employer employer0 = new Employer();
      Employee[] employeeArray0 = new Employee[6];
      employer0.addEmployees(employeeArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Employer employer0 = new Employer();
      employer0.setEmployerName("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Employer employer0 = new Employer();
      String string0 = employer0.getEmployerName();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Employer employer0 = new Employer();
      List<Employee> list0 = employer0.getEmployees();
      employer0.setEmployerAttributes(639, "8FQ&d^<", list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Employer employer0 = new Employer();
      List<Employee> list0 = employer0.getEmployees();
      Employer employer1 = new Employer((-1), "8FQ&d^<", list0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Employer employer0 = new Employer();
      int int0 = employer0.getEmployerId();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Employer employer0 = new Employer();
      employer0.setEmployerId((-1));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Employer employer0 = new Employer();
      List<Employee> list0 = employer0.getEmployees();
      employer0.setEmployees(list0);
  }
}
