/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 19 11:33:06 GMT 2022
 */

package irs;

import org.junit.Test;
import static org.junit.Assert.*;
import irs.Salary;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Salary_ESTest extends Salary_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Salary salary0 = new Salary();
      salary0.setSalary((-2326));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Salary salary0 = new Salary();
      double double0 = salary0.getSalary();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Salary salary0 = new Salary();
      salary0.setEmployeeId((-2326));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Salary salary0 = new Salary();
      int int0 = salary0.getEmployeeId();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Salary salary0 = new Salary();
      salary0.setEmployerId((-3640));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Salary salary0 = new Salary();
      int int0 = salary0.getEmployerId();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Salary salary0 = new Salary((-400), (-400), (-1452.7313083));
  }
}
