import os

# name of default config file
TKLTEST_DEFAULT_CONFIG_FILE='tkltest_config.toml'

# name of (hidden) config file created by generate command (to be used by the execute command)
TKLTEST_GENERATE_CONFIG_FILE='.tkltest_generate.toml'

# lib download dir
TKLTEST_LIB_DIR = 'lib'
TKLTEST_LIB_DOWNLOAD_DIR = os.path.join(TKLTEST_LIB_DIR, 'download')

# suffix for the default test directory name (used if test directory is unspecified)
# CTD amplified tests
TKLTEST_DEFAULT_CTDAMPLIFIED_TEST_DIR_SUFFIX = "-ctd-amplified-tests"
# Randoop standalone tests
TKLTEST_DEFAULT_RANDOOP_TEST_DIR_SUFFIX = "-randoop-standalone-tests"
# EvoSuite standalone tests
TKLTEST_DEFAULT_EVOSUITE_TEST_DIR_SUFFIX = "-evosuite-standalone-tests"

# suffix for the directory containing test reports (CTD, junit, jacoco); names of the 
# sub-directories for different reports
TKLTEST_MAIN_REPORT_DIR_SUFFIX = '-tkltest-reports'
TKL_CTD_REPORT_DIR = 'ctd-report'
TKL_JUNIT_REPORT_DIR = 'junit-reports'
TKL_CODE_COVERAGE_REPORT_DIR = 'jacoco-reports'

# suffix for the file containing the CTD model and test plan
TKL_CTD_TEST_PLAN_FILE_SUFFIX = '_ctd_models_and_test_plans.json'

# suffix for the file containing the building-block test sequences
TKL_BB_SEQ_FILE_SUFFIX = '_bb_test_sequences.json'

# name of the CTD coverage file generated by the test sequence extender
TKL_EXTENDER_COVERAGE_FILE = 'coverage_report.json'

# name of summary file created by the sequence extender
TKL_EXTENDER_SUMMARY_FILE = 'test_generation_summary.json'

# name of test generator indicating use of all existing test generators in concert
COMBINED_TEST_GENERATOR_NAME = 'CombinedTestGenerator'

# mapping of base test generator names specified in CLI option to the internal name
# or name of the corresponding code component
BASE_TEST_GENERATORS = {
    'combined': COMBINED_TEST_GENERATOR_NAME,
    'evosuite': 'EvoSuiteTestGenerator',
    'randoop': 'RandoopTestGenerator'
}

# suffix for the file containing the CTD model and test plan
ERROR_PATTERNS_FILE = 'errorPatterns.json'

# randoop used version
RANDOOP_VERSION = "4.2.6"

# evosuite used version
EVOSUITE_VERSION = "1.0.7"

# soot used version
SOOT_VERSION = "4.1.0"
