name: Testgen-CLI CI

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install prerequisites
      run: |
        ant -version
        sudo apt-get install -y bats libxml2-utils
        bats --version
        xmllint --version
#    - name: Create maven settings.xml
#      uses: s4u/maven-settings-action@v2.4.0
#      with:
#        servers: '[
#          {"id": "github", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"},
#          {"id": "github-sinha108", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"}
#        ]'
    - name: Download Java libraries
      run: |
        cd lib
        sed -ie "s|GITHUB_USERNAME|$GITHUB_ACTOR|g" settings.xml
        sed -ie "s|GITHUB_TOKEN|${{ secrets.TKLTEST_PKGS_PAT }}|g" settings.xml
        cat ./settings.xml
        ./download_lib_jars.sh
        cd ..; ls lib/*
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python unit tests
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64
      run: |
        nosetests test/test_config.py test/test_tkltest.py test/test_generate_execute.py
    - name: Install CLI command and run bats tests
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install .
        which tkltest
        bats test/test_cli.bats
        bats test/test_cli_irs.bats
