name: TackleTest-Unit CI

on:
  push:
    paths-ignore:
      - 'tkltest/generate/ui/**'
      - 'tkltest/execute/ui/**'
      - 'tkltest/util/ui/**'
      - 'tkltest/tkltest_ui.py'
      - 'tkltest-lib/pom_ui.xml'
      - 'doc/**'
      - '**.md'
      - '.github/workflows/tkltest_ui_ci.yml'
      - '.gitattributes'
      - 'test/ui/**'
  pull_request:
    paths-ignore:
      - 'tkltest/generate/ui/**'
      - 'tkltest/execute/ui/**'
      - 'tkltest/util/ui/**'
      - 'tkltest/tkltest_ui.py'
      - 'tkltest-lib/pom_ui.xml'
      - 'doc/**'
      - '**.md'
      - '.github/workflows/tkltest_ui_ci.yml'
      - '.gitattributes'
      - 'test/ui/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install prerequisites
      run: |
        ant -version
        sudo apt-get update && sudo apt-get install -y bats libxml2-utils
        bats --version
        xmllint --version
        gradle --version
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - name: Download Java libraries
      run: |
        gradle --version
        cd tkltest-lib
        ./download_lib_jars.sh
        cd ..; ls tkltest-lib/*
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python unit tests
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64
      run: |
        nosetests test/unit/test_config.py test/unit/test_tkltest.py test/unit/test_unit_tests.py
        nosetests test/unit/test_generate_execute.py
    - name: Install tkltest-unit command and run bats tests
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64
      run: |
        git submodule init
        git submodule update
        python -m venv venv
        source venv/bin/activate
        pip install .
        which tkltest-unit
        bats test/unit/test_cli.bats
        bats test/unit/test_cli_irs.bats
        deactivate
    - name: Run tkltest-unit bats tests using docker-compose
      run: |
        bats test/test_cli_docker.bats
